# Advanced operations


In [1]:
#import paskages
import tensorflow as tf

In [3]:
#define X
x=tf.Variable(-1.0)
x.numpy()

-1.0

In [4]:
#dfine y within instancs GradientTape

with tf.GradientTape() as tape:
    tape.watch(x)
    y=tf.multiply(x,x)

In [6]:
#evaluate
g= tape.gradient(y,x)
g.numpy()

-2.0

In [15]:
#generate grayscale image
gray = tf.random.uniform([2,2] , maxval=255 , dtype='int32')
#reshape grayscale
gray =tf.reshape(gray , [4,1])
gray

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[229],
       [ 68],
       [245],
       [191]])>

In [18]:
#generate color image
color = tf.random.uniform([2,2,3] , maxval=255 , dtype='int32')

#reshape color image
color = tf.reshape(color , [4,3])
color

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[233, 105, 116],
       [166, 142, 152],
       [144, 118,  41],
       [ 78,  31,  23]])>

In [17]:
#ex2 generate grayscale image
gray2 = tf.random.uniform([ 3,3] ,maxval=60, dtype='int32' )
gray2 =  tf.reshape(gray2 ,[9,1])
gray2

<tf.Tensor: shape=(9, 1), dtype=int32, numpy=
array([[57],
       [19],
       [59],
       [26],
       [ 6],
       [46],
       [32],
       [37],
       [46]])>

###### Exercise


###### Reshaping tensors


In [ ]:
# Reshape the grayscale image tensor into a vector
gray_vector = reshape(gray_tensor, (784, 1))

# Reshape the color image tensor into a vector
color_vector = reshape(color_tensor, (2352, 1))

In [23]:
def compute_gradient(x0):
  	# Define x as a variable with an initial value of x0
	x = tf.Variable(x0)
	with tf.GradientTape() as tape:
		tape.watch(x)
        # Define y using the multiply operation
		y = tf.multiply(x, x)
    # Return the gradient of y with respect to x
	return tape.gradient(y, x).numpy()

# Compute and print gradients at x = -1, 1, and 0
print(compute_gradient(-1.0))
print(compute_gradient(1.0))
print(compute_gradient(0.0))

-2.0
2.0
0.0


In [ ]:
# Reshape model from a 1x3 to a 3x1 tensor
model = reshape(model, (3, 1))

# Multiply letter by model
output = matmul(letter, model)

# Sum over output and print prediction using the numpy method
prediction = reduce_sum(output)
print(prediction.numpy())