# Basic operations


In [37]:
#import
import tensorflow as tf
from tensorflow import constant, add
from tensorflow import ones , matmul , multiply ,reduce_sum,ones_like

In [4]:
#define 0-d tenssors
A0 = constant([1])
B0 =constant([2])


In [5]:
#define 1-d tensors
A1= constant([1,2])
B1=constant([3,4])

In [6]:
#define 2-d tensors
A2= constant( [ [1,2],[3,4]  ]  )
B2= constant( [  [5,6] , [7,8]       ] )


In [9]:
#perform tensor addition with add()
c0 = add(A0 , B0)
c1= add(A1 , B1)
c2=add(A2,B2)


In [14]:
# define tensors
A0 = ones(1)
A31=ones([3,1])
A34=ones([3,4])
A43=ones([4,3])

In [16]:
#define a 2*3*4
A= ones([2,3,4])

In [20]:
#sum over all D
B=reduce_sum(A)
B

<tf.Tensor: shape=(), dtype=float32, numpy=24.0>

In [21]:
# sum over dimensions 0,1 and 2
B0 = reduce_sum(A,0)
B1=reduce_sum(A,1)
B2= reduce_sum(A,2)

In [35]:
A888=ones([6,7,8,9,10])
reduce_sum(A888,4)

<tf.Tensor: shape=(6, 7, 8, 9), dtype=float32, numpy=
array([[[[10., 10., 10., ..., 10., 10., 10.],
         [10., 10., 10., ..., 10., 10., 10.],
         [10., 10., 10., ..., 10., 10., 10.],
         ...,
         [10., 10., 10., ..., 10., 10., 10.],
         [10., 10., 10., ..., 10., 10., 10.],
         [10., 10., 10., ..., 10., 10., 10.]],

        [[10., 10., 10., ..., 10., 10., 10.],
         [10., 10., 10., ..., 10., 10., 10.],
         [10., 10., 10., ..., 10., 10., 10.],
         ...,
         [10., 10., 10., ..., 10., 10., 10.],
         [10., 10., 10., ..., 10., 10., 10.],
         [10., 10., 10., ..., 10., 10., 10.]],

        [[10., 10., 10., ..., 10., 10., 10.],
         [10., 10., 10., ..., 10., 10., 10.],
         [10., 10., 10., ..., 10., 10., 10.],
         ...,
         [10., 10., 10., ..., 10., 10., 10.],
         [10., 10., 10., ..., 10., 10., 10.],
         [10., 10., 10., ..., 10., 10., 10.]],

        ...,

        [[10., 10., 10., ..., 10., 10., 10.],
         [

##### Exercise


###### Performing element-wise multiplication


In [38]:
# Define tensors A1 and A23 as constants
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = ones_like(A1)
B23 = ones_like(A23)

# Perform element-wise multiplication
C1 = multiply(A1, B1)
C23 = multiply(A23, B23)

# Print the tensors C1 and C23
print('\n C1: {}'.format(C1.numpy()))
print('\n C23: {}'.format(C23.numpy()))


 C1: [1 2 3 4]

 C23: [[1 2 3]
 [1 6 4]]


###### Making predictions with matrix multiplication


In [40]:
# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = constant([[1000], [150]])
bill = constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = matmul(features, params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]
