# Constants and variables


In [13]:
#import paskages
import tensorflow as tf
from tensorflow import constant

In [4]:
 #0D Tensor
d0 = tf.ones(1)
d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [5]:
#1D
d1 = tf.ones((2,))
d1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [6]:
#2D
d2=tf.ones((2,2))
d2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [11]:
#3D
d3= tf.ones((2,2,2))
d3

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [12]:
#orint 3d tensor
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [16]:
# define 2*3 constant
a = constant(3 , shape=[2,3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]])>

In [17]:
#define a 2*2 constant
b = constant([1,2,3,4] , shape=[2,2])
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [25]:
tf.fill([2,2],7)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 7],
       [7, 7]])>

In [27]:
#define variable
a0 = tf.Variable([1,2,3,4,5,6] , dtype=tf.float32)
a1 = tf.Variable([1,2,3,4,5,6] , dtype=tf.int16)

In [31]:
#define a constant
b= tf.constant(2 , tf.float32)
b

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [32]:
# compute their product
c0 = tf.multiply(a0,b)
c1=a0*b

##### Exercise


###### Defining data as constants


###### Defining variables


In [36]:
# Define the 1-dimensional variable A1
A1 = tf.Variable([1, 2, 3, 4])

# Print the variable A1
print('\n A1: ', A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print('\n B1: ', B1)


 A1:  <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

 B1:  [1 2 3 4]
